using Stump.Core.IO;
using Stump.DofusProtocol.D2oClasses;
using Stump.DofusProtocol.D2oClasses.Tools.D2o;
using Stump.ORM;
using Stump.ORM.SubSonic.SQLGeneration.Schema;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NewTool.Records
{
    public class AchievementCategoryRelator
    {
        public static string FetchQuery = "SELECT * FROM achievements_categories";
    }

    [TableName("achievements_categories")]
    public class AchievementCategoryRecord : IAutoGeneratedRecord
    {
        private uint[] m_achievementsIds;
        private string m_achievementsIdsCSV;

        [PrimaryKey("Id", false)]
        public uint Id
        {
            get;
            set;
        }
        public uint NameId
        {
            get;
            set;
        }
        public uint ParentId
        {
            get;
            set;
        }
        //[Ignore]
        //public AchievementCategoryRecord Parent
        //{
        //    get
        //    {
        //        if (this.ParentId > 0)
        //        {
        //            if (this.m_parent == null)
        //            {
        //                this.m_parent = Singleton<AchievementManager>.Instance.TryGetAchievementCategory(this.ParentId);
        //            }
        //        }

        //        return this.m_parent;
        //    }
        //}
        [NullString]
        public string Icon
        {
            get;
            set;
        }
        public uint Order
        {
            get;
            set;
        }

        [NullString]
        public string Color
        {
            get;
            set;
        }

        [Ignore]
        public uint[] AchievementsIds
        {
            get
            {
                return this.m_achievementsIds;
            }
            set
            {
                this.m_achievementsIds = value;
                this.m_achievementsIdsCSV = value.ToCSV(",");
            }
        }

        public string AchievementsIdsCSV
        {
            get
            {
                return this.m_achievementsIdsCSV;
            }
            set
            {
                this.m_achievementsIdsCSV = value;
                this.m_achievementsIds = value.FromCSV<uint>(",");
            }
        }

        public virtual void AssignFields(object d2oObject)
        {
            var item = (AchievementCategory)d2oObject;
            this.Id = item.id;
            this.NameId = item.nameId;
            this.ParentId = item.parentId;
            this.Icon = item.icon;
            this.Order = item.order;
            this.Color = item.color;
            this.AchievementsIds = item.achievementIds.ToArray();
        }
    }
}
